### ISSUE TITLE
Awesome work - Needs more polishing and features

### ISSUE THREAD

**Issue by xoraingroup** [NBPub/BeatLog#1]
Hi there,

  I have found it from reddit and it looks pretty good. However I have come across many similar tools like this, like goaccess, awsstats etc.

I would like you to make it unique in a way that it just not act as a tool, but provides an API as well to query data easily.

For example I want to query total bandwidth used for a specific url being access by viewers.

curl http://beatlog/api/bandwidth?url=https://abc.com/some.png&server=some-node-01

or 

Getting total visitors from last 2 hours via API. This is just an idea, but no one provides such tool. Also what you can make this tool as a daemon which can get access logs on the fly and continously parses them and store information in database.

Overall good project 👍

**Comment by NBPub** [comment]
Thanks for the kind words. An API for queries is a great idea. I'm [thinking](https://github.com/NBPub/BeatLog#planned-improvements) of adding a page to facilitate data selection, and think I could build this alongside API data queries.

Bandwidth seems relatively straightforward to serve, it could be total (or average/min/max/range) for a particular time range with other selections. For other things, I'm wondering if it's worth responding with tabular data - whether as an HTML block or a JSON response. Let me know if you have thoughts. I'll work on simple stuff for now, and close the issue with some progress.

This tool should function as a daemon, in that log parsing and database updates can be [scheduled](https://github.com/NBPub/BeatLog/tree/main/docs#scheduled-tasks). 

I don't think it will be as efficient as goaccess, like you mentioned, so I don't think it's worth scanning more often than 1/hour. Even though a convenient [SWAG addon](https://www.linuxserver.io/blog/introducing-swag-dashboard) for goaccess was made, I like using this tool for the more detailed fail2ban integration and the classification of my home and "known device" connections.  It's nice to put the server traffic in buckets before I analyze the data.

**Comment by NBPub** [comment]
Closing with the addition of 2 new features:

1. **[Database Explorer](https://github.com/NBPub/BeatLog/blob/main/docs/NullConnectionPool.md#background)** - select from various SQL query options and view returned tables
2. **[JSON API](https://github.com/NBPub/BeatLog/blob/main/docs/API.md#simple-json-api)** - select from a few options, get data summary from past 24 hours

I may expand the API over time, starting by allowing a time selection and not just defaulting to the past day.

**Comment by NBPub** [comment]
hopefully closing this time

**Comment by xoraingroup** [comment]
Very sorry for late reply. :)

This is the right direction you are going. These are awesome improvements to the tool.

Is it possible to get data for specific string in accessed url. For example

Http://beatlog/static_1345_abcdef

So basically I want to get total bandwidth used for above kind of url when I pass a query parameter (static_1345_abcdef) to the api u built. 

Thank you and sorry once again for late reply. I can put a new issue if you want as this issue is already closed. 

Many thanks once again.

**Comment by NBPub** [comment]
**Edit: I've made some progress today, so I created [new issue](https://github.com/NBPub/BeatLog/issues/2). Please direct any feedback there**

No problem, thanks for responding. For this, I think a new issue would be a good way to organize thoughts.

> Is it possible to get data for specific string in accessed url. For example
> 
> [Http://beatlog/static_1345_abcdef](Http://beatlog/static_1345_abcdef)
> 
> So basically I want to get total bandwidth used for above kind of url when I pass a query parameter (static_1345_abcdef) to the api u built.

I can make a "call" for that on the API. For now, I will only have it search by URL, but later I can add other parameters/filters. Would you want the data for a particular time period, or for the entire database?

**Comment by xoraingroup** [comment]
Well both are ok, as for particular time it gives you more flexibility to get stats for that specific period. 

Let me put more option in the other issue. Lets follow that up.
