### ISSUE TITLE
API v2 - bandwidth

### ISSUE THREAD

**Issue by NBPub** [NBPub/BeatLog#2]
# [BeatLog API](https://github.com/NBPub/BeatLog/blob/main/docs/API.md#simple-json-api) Enhancement

## API~~v2~~ Bandwidth

*changing back to "v1" in code, apologies for any confusion*

### *Please provide any commentary on what additions or changes to the feature you'd like to see*
---
### Goal
Provide total bandwidth for a specific URL from the database. See [here](https://github.com/NBPub/BeatLog/issues/1#issuecomment-1432071411).

### Current State

*available as "latest" tag. keeping [API documentation](https://github.com/NBPub/BeatLog/blob/main/docs/API.md#bandwidth) more up to date than examples on this comment.*

Provides total bandwidth in bytes, in "pretty" form as a string, and the associated query parameters. 
Visit: `<your_site>/api/v2/bandwidth/<FIELD>=<VALUE>`

This will provide total bandwidth from the **Access Log** table in the database. The available `<FIELD>`'s are listed as columns in the [documentation](https://github.com/NBPub/BeatLog/tree/main/docs#access-logs---access). So one can query against more than just the "URL". Note that **URL** and **Referrer** are separate columns. I have not done any encoding/decoding for values yet, so some URLs or other values may cause errors or return invalid results. If the SQL query returns no data, values will be `null`.

### Examples

*going to edit links to refer to future documentation*

[<your_site>/api/v2/bandwidth/url=/robots.txt](https://github.com/NBPub/BeatLog/blob/main/docs/API.md#simple-json-api)
```json
{
  "bandwidth": {
    "bytes": 44591,
    "pretty": "44 kB",
    "query": {
      "field": "url",
      "value": "/robots.txt"
    }
  }
}
````

[<your_site>/api/v2/bandwidth/url=/](https://github.com/NBPub/BeatLog/blob/main/docs/API.md#simple-json-api)
```json
{
  "bandwidth": {
    "bytes": 2649868,
    "pretty": "2588 kB",
    "query": {
      "field": "url",
      "value": "/"
    }
  }
}
````

*no URL in database matches value*
[<your_site>/api/v2/bandwidth/url=65456](https://github.com/NBPub/BeatLog/blob/main/docs/API.md#simple-json-api)
```json
{
  "bandwidth": {
    "bytes": null,
    "pretty": null,
    "query": {
      "field": "url",
      "value": "65465"
    }
  }
}
```

*HTTP version is multiplied by 10 to store as an integer in the table*

[<your_site>/api/v2/bandwidth/http=11](https://github.com/NBPub/BeatLog/blob/main/docs/API.md#simple-json-api)
```json
{
  "bandwidth": {
    "bytes": 1861382265,
    "pretty": "1775 MB",
    "query": {
      "field": "http",
      "value": "11"
    }
  }
}
````

[<your_site>/api/v2/bandwidth/http=20](https://github.com/NBPub/BeatLog/blob/main/docs/API.md#simple-json-api)
```json
{
  "bandwidth": {
    "bytes": 59052004142,
    "pretty": "55 GB",
    "query": {
      "field": "http",
      "value": "20"
    }
  }
}
````

### Next

 * ~~**Should # rows be provided with data?**~~
   * added number of connections as "hits", and provide "data_per_hit", see docs
 * Allow for specifying `NULL`?
 * bugfixes
   * date inputs won't work without conversion to timestamp, disable / add warning / catch error ?
   * location match only available via **geoinfo** table rowid. not intuitive.
     * could add API feature to list all geo data (row id, city, country, coordinates)

**Comment by xoraingroup** [comment]
The above are the best use cases to start. 

Filtering by some string in URL would be perfect. I can write down some points to extend api spec.

1. Get bandwidth based on certain string in the url i.e. filtering using regex etc 
2. Data retention initially based on time period or an api call with start and end parameter with unix timestamps.
3. ingestion of logs on UDP / TCP port along with local file logs in real time and storing metrics.

The point 3 is good in a way that it makes it a centralized point of aggregating logs from different servers and storing metrics in database. A schema can be designed for ingestion as what kind of format will be expected by BeatLog. 

I will leave the following point as a kind of future improvement when point 3 is done.

4. Achieving HA for Beatlog as a service with distributed architecture.

I will keep putting more feedbacks here. Thank you for your awesome work.

**Comment by NBPub** [comment]
Thanks for the feedback. I plan to address points 1 and 2 with the next stable release, and comment here again when it's ready.

  1. I believe the string matching can be done directly with a Postgresql query, so that should be easy.
  2. I will add date selection to the `bandwidth` api call. It can be done alone or added to an existing query. I like using UNIX timestamps.
  3. You could make another issue for this, however it does not fit my usecase for **BeatLog**. 
    - I don't think it would be hard to allow for multiple "access", "fail2ban", and "error" logs. 
    - If you provide sample logs, I could start a separate fork of **BeatLog** to handle multiple log sources.
  4. Do you mean running this concurrently on different hosts? I think that would be outside the scope of **BeatLog**. On a reliable system, it should have "HA", and its container could be deployed via Kubernetes or something similar.

**Comment by NBPub** [comment]
did not mean to close. . .

**Comment by xoraingroup** [comment]
> 3\. You could make another issue for this, however it does not fit my usecase for **BeatLog**.
>     - I don't think it would be hard to allow for multiple "access", "fail2ban", and "error" logs.
>     - If you provide sample logs, I could start a separate fork of **BeatLog** to handle multiple log sources.

It was more of like extending beatlog functionality. A kind of central ingestion service that can take logs from different sources other than local files.

For point 4 if the beatlog serves as a ingestion service and parsing metrics in some database, then HA is easy via k8s, bearmetal or even docker-compose.

**Comment by NBPub** [comment]
The **Bandwidth** call has been added to the JSON API in the **alpha-0.1.5** release. I may may some tweaks in future versions, but the basic call syntax and data return should remain the same.

[alpha-0.1.5 release "stable"](https://github.com/NBPub/BeatLog/releases/tag/alpha-0.1.5)

[API documentation](https://github.com/NBPub/BeatLog/blob/main/docs/API.md#simple-json-api), [Bandwidth section](https://github.com/NBPub/BeatLog/blob/main/docs/API.md#bandwidth)

*Documentation may be updated, if any significant changes are made to the API code I will make another stable release, **alpha-0.1.6***
